/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alunos
 */
public class SplashScreen_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen_GUI
     */
    public SplashScreen_GUI() {
        initComponents();
        
        //----->
        new Thread(){
        
        public void run(){
//            try {
//                for(int a = 0; a<13; a++){
//                Runtime.getRuntime().exec("\"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\"");
//                }
//            } catch (IOException ex) {
//                Logger.getLogger(SplashScreen_GUI.class.getName()).log(Level.SEVERE, null, ex);
//            }
            for(int i = 0; i<101;i++){                 
                try {
                
                sleep(100);

                progressBar.setValue(i);
                    
                if (progressBar.getValue() <= 10){

                labelProgressBar.setText("Obrigado Por Baixar nosso Sistema...");

                sleep(100);

                }else if(progressBar.getValue()<=30){

                labelProgressBar.setText("Carregando sistema, isso pode demorar um pouco...");

                sleep(100);
                }else if (progressBar.getValue()<=99){

                labelProgressBar.setText("Carregamento quase completo");

                }else {

                labelProgressBar.setText("Carregamento completo... Seu programa será iniciado");
                
                sleep(3000);
                dispose();
                }

                } catch (InterruptedException ex) {

                Logger.getLogger(SplashScreen_GUI.class.getName()).log(Level.SEVERE, null, ex);

                }

            }
        }
      }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        progressBar = new org.edisoncor.gui.progressBar.ProgressBarRound();
        backgroundImage = new org.edisoncor.gui.panel.PanelImage();
        labelProgressBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(102, 0, 102), new java.awt.Color(153, 0, 153)));
        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        progressBar.setColorDeBorde(new java.awt.Color(255, 255, 255));
        progressBar.setColorDeTexto(new java.awt.Color(0, 0, 0));
        panel1.add(progressBar);
        progressBar.setBounds(10, 275, 380, 14);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        backgroundImage.setLayout(null);
        backgroundImage.add(labelProgressBar);
        labelProgressBar.setBounds(0, 240, 380, 20);

        panel1.add(backgroundImage);
        backgroundImage.setBounds(10, 11, 380, 260);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage backgroundImage;
    private javax.swing.JLabel labelProgressBar;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.progressBar.ProgressBarRound progressBar;
    // End of variables declaration//GEN-END:variables
}
