/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class Salas_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Salas_GUI
     */
    public Salas_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContainer = new org.edisoncor.gui.panel.Panel();
        panelRoom = new org.edisoncor.gui.panel.Panel();
        labelSala1 = new org.edisoncor.gui.label.LabelCustom();
        labelSala2 = new org.edisoncor.gui.label.LabelCustom();
        labelSala3 = new org.edisoncor.gui.label.LabelCustom();
        labelSala4 = new org.edisoncor.gui.label.LabelCustom();
        labelSala5 = new org.edisoncor.gui.label.LabelCustom();
        panelMenu = new org.edisoncor.gui.panel.Panel();
        labelSalas = new org.edisoncor.gui.label.LabelCustom();
        labelSalas1 = new org.edisoncor.gui.label.LabelCustom();
        labelSalas2 = new org.edisoncor.gui.label.LabelCustom();
        labelSalas3 = new org.edisoncor.gui.label.LabelCustom();
        labelSalas4 = new org.edisoncor.gui.label.LabelCustom();
        panelStatus = new org.edisoncor.gui.panel.Panel();
        sala00 = new javax.swing.JButton();
        sala1 = new javax.swing.JButton();
        sala2 = new javax.swing.JButton();
        sala3 = new javax.swing.JButton();
        sala4 = new javax.swing.JButton();
        sala5 = new javax.swing.JButton();
        sala6 = new javax.swing.JButton();
        sala7 = new javax.swing.JButton();
        sala8 = new javax.swing.JButton();
        sala9 = new javax.swing.JButton();
        sala10 = new javax.swing.JButton();
        sala11 = new javax.swing.JButton();
        sala12 = new javax.swing.JButton();
        sala13 = new javax.swing.JButton();
        sala14 = new javax.swing.JButton();
        sala15 = new javax.swing.JButton();
        sala16 = new javax.swing.JButton();
        sala17 = new javax.swing.JButton();
        sala18 = new javax.swing.JButton();
        sala19 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelContainer.setLayout(null);

        panelRoom.setLayout(new java.awt.GridLayout(5, 0));

        labelSala1.setBackground(new java.awt.Color(204, 204, 204));
        labelSala1.setText("Sala");
        labelSala1.setDireccionDeSombra(100);
        panelRoom.add(labelSala1);

        labelSala2.setBackground(new java.awt.Color(204, 204, 204));
        labelSala2.setText("Sala");
        labelSala2.setDireccionDeSombra(100);
        panelRoom.add(labelSala2);

        labelSala3.setBackground(new java.awt.Color(204, 204, 204));
        labelSala3.setText("Sala");
        labelSala3.setDireccionDeSombra(100);
        panelRoom.add(labelSala3);

        labelSala4.setBackground(new java.awt.Color(204, 204, 204));
        labelSala4.setText("Sala");
        labelSala4.setDireccionDeSombra(100);
        panelRoom.add(labelSala4);

        labelSala5.setBackground(new java.awt.Color(204, 204, 204));
        labelSala5.setText("Sala");
        labelSala5.setDireccionDeSombra(100);
        panelRoom.add(labelSala5);

        panelContainer.add(panelRoom);
        panelRoom.setBounds(0, 50, 90, 230);

        panelMenu.setLayout(new java.awt.GridLayout());

        labelSalas.setBackground(new java.awt.Color(153, 153, 153));
        labelSalas.setText("Salas");
        labelSalas.setDireccionDeSombra(100);
        panelMenu.add(labelSalas);

        labelSalas1.setBackground(new java.awt.Color(153, 153, 153));
        labelSalas1.setText("8:00");
        labelSalas1.setDireccionDeSombra(100);
        panelMenu.add(labelSalas1);

        labelSalas2.setBackground(new java.awt.Color(153, 153, 153));
        labelSalas2.setText("8:30");
        labelSalas2.setDireccionDeSombra(100);
        panelMenu.add(labelSalas2);

        labelSalas3.setBackground(new java.awt.Color(153, 153, 153));
        labelSalas3.setText("9:00");
        labelSalas3.setDireccionDeSombra(100);
        panelMenu.add(labelSalas3);

        labelSalas4.setBackground(new java.awt.Color(153, 153, 153));
        labelSalas4.setText("9:30");
        labelSalas4.setDireccionDeSombra(100);
        panelMenu.add(labelSalas4);

        panelContainer.add(panelMenu);
        panelMenu.setBounds(0, 0, 400, 50);

        panelStatus.setLayout(new java.awt.GridLayout(5, 4));

        sala00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sala00MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        sala00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala00ActionPerformed(evt);
            }
        });
        panelStatus.add(sala00);

        sala1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala1);

        sala2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala2);

        sala3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala3);

        sala4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala4);

        sala5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala5);

        sala6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala6);

        sala7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala7);

        sala8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala8);

        sala9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala9);

        sala10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala10);

        sala11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala11);

        sala12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala12);

        sala13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala13);

        sala14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala14);

        sala15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala15);

        sala16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala16);

        sala17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala17);

        sala18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala18);

        sala19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salasMouseEntered(evt);
            }
        });
        panelStatus.add(sala19);

        panelContainer.add(panelStatus);
        panelStatus.setBounds(90, 50, 310, 230);

        getContentPane().add(panelContainer);
        panelContainer.setBounds(0, 0, 400, 280);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Ver Salas");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salasMouseEntered
        System.out.print(this);
    }//GEN-LAST:event_salasMouseEntered

    private void sala00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sala00MouseClicked
        this.setBackground(Color.red);
    }//GEN-LAST:event_sala00MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null,"Você realmente deseja sair?");
        if(resp == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void sala00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala00ActionPerformed
        setBackground(Color.yellow);
    }//GEN-LAST:event_sala00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salas_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private org.edisoncor.gui.label.LabelCustom labelSala1;
    private org.edisoncor.gui.label.LabelCustom labelSala2;
    private org.edisoncor.gui.label.LabelCustom labelSala3;
    private org.edisoncor.gui.label.LabelCustom labelSala4;
    private org.edisoncor.gui.label.LabelCustom labelSala5;
    private org.edisoncor.gui.label.LabelCustom labelSalas;
    private org.edisoncor.gui.label.LabelCustom labelSalas1;
    private org.edisoncor.gui.label.LabelCustom labelSalas2;
    private org.edisoncor.gui.label.LabelCustom labelSalas3;
    private org.edisoncor.gui.label.LabelCustom labelSalas4;
    private org.edisoncor.gui.panel.Panel panelContainer;
    private org.edisoncor.gui.panel.Panel panelMenu;
    private org.edisoncor.gui.panel.Panel panelRoom;
    private org.edisoncor.gui.panel.Panel panelStatus;
    private javax.swing.JButton sala00;
    private javax.swing.JButton sala1;
    private javax.swing.JButton sala10;
    private javax.swing.JButton sala11;
    private javax.swing.JButton sala12;
    private javax.swing.JButton sala13;
    private javax.swing.JButton sala14;
    private javax.swing.JButton sala15;
    private javax.swing.JButton sala16;
    private javax.swing.JButton sala17;
    private javax.swing.JButton sala18;
    private javax.swing.JButton sala19;
    private javax.swing.JButton sala2;
    private javax.swing.JButton sala3;
    private javax.swing.JButton sala4;
    private javax.swing.JButton sala5;
    private javax.swing.JButton sala6;
    private javax.swing.JButton sala7;
    private javax.swing.JButton sala8;
    private javax.swing.JButton sala9;
    // End of variables declaration//GEN-END:variables
}
